
server:
  port: 80

# 콘솔 ANSI 색상
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${s.username}
    password: ${s.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  output:
    ansi:
      enabled: always

# ThymeLeaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:templates/views/

# datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostnmae}:${rds.host}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${user}
    password: ${password}

  # security
  security:
    user:
      name: ${d.user}
      password: ${d.password}

    # oauth2 client
    oauth2:
      client:
        registration:
          google:
            client-id: ${g.clientId}
            client-secret: ${g.clientPassword}
            scope:
              - email
              - profile
          naver:
            client-id: ${n.clientId}
            client-secret: ${n.clientPassword}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        # provider 제공(google 과 facebook는 기본으로 제공함)
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

mybatis:
 mapper-locations: classpath:mapper/**/*.xml


app:
  # 파일 업로드 경로
  upload:
    path: upload

  # 페이징 관련 세팅값
  pagination:
    write_pages: 10
    page_rows: 12

  oauth2:

    password: ${o.password}


    kakao:
      client-id: ${k.clientId}
      redirect-uri: http://localhost:8080/oauth2/kakao/callback
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me




